// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
require('chromedriver');
const fs = require('fs');
const _ = require('lodash');

const openAndWait = async function(driver, term, time) {
	await driver.get("https://www.walmart.com/search?query="+ encodeURIComponent(term));
	return new Promise(function(succ) {
		setTimeout(succ, time);
	});
};

describe('walmart', async function() {
  this.timeout(30000000);
  let driver;
  let vars;
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  });
  afterEach(async function() {
    await driver.quit();
  });
  const groceries = _.shuffle(fs.readFileSync('./data/groceries.txt').toString().split('\n').map(pr=>_.trim(pr, '\n\r\t ".,')));
  it('groceries', async function() {
    //Wait for install of extension
    await openAndWait(driver, 'bread', 20000);
    for(let key in groceries) {
      const v = groceries[key];
      await openAndWait(driver, v, 20000)
    }
  })
})
