// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert');
require('chromedriver');

const openAndWait = async function(driver, zip, time) {
	await driver.get("https://www.zillow.com/willow-ak/"+ zip);
	return new Promise(function(succ) {
		setTimeout(succ, time);
	});
};

describe('test_enter', function() {
  this.timeout(30000000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_enter', async function() {
    //Wait for install of extension
    await openAndWait(driver, 60629, 100000);
    const postcodes = [60628, 60627];
    for(let key in postcodes) {
      const v = postcodes[key];
      await openAndWait(driver, v, 10000)
    }
  })
});
